import { CRYPTO_CURRENCIES } from './crypto-currencies';

export interface Currency {
  code: string;
  name: string;
  nameKo: string;
  symbol: string;
  flag: string;
}

/** 150개 글로벌 통화 메타데이터. */
export const CURRENCIES: Currency[] = [
  // ── Americas ──
  { code: 'usd', name: 'US Dollar', nameKo: '미국 달러', symbol: '$', flag: '🇺🇸' },
  { code: 'cad', name: 'Canadian Dollar', nameKo: '캐나다 달러', symbol: 'C$', flag: '🇨🇦' },
  { code: 'mxn', name: 'Mexican Peso', nameKo: '멕시코 페소', symbol: '$', flag: '🇲🇽' },
  { code: 'brl', name: 'Brazilian Real', nameKo: '브라질 헤알', symbol: 'R$', flag: '🇧🇷' },
  { code: 'ars', name: 'Argentine Peso', nameKo: '아르헨티나 페소', symbol: '$', flag: '🇦🇷' },
  { code: 'clp', name: 'Chilean Peso', nameKo: '칠레 페소', symbol: '$', flag: '🇨🇱' },
  { code: 'cop', name: 'Colombian Peso', nameKo: '콜롬비아 페소', symbol: '$', flag: '🇨🇴' },
  { code: 'pen', name: 'Peruvian Sol', nameKo: '페루 솔', symbol: 'S/', flag: '🇵🇪' },
  { code: 'uyu', name: 'Uruguayan Peso', nameKo: '우루과이 페소', symbol: '$U', flag: '🇺🇾' },
  { code: 'bob', name: 'Bolivian Boliviano', nameKo: '볼리비아 볼리비아노', symbol: 'Bs', flag: '🇧🇴' },
  { code: 'pyg', name: 'Paraguayan Guarani', nameKo: '파라과이 과라니', symbol: '₲', flag: '🇵🇾' },
  { code: 'ves', name: 'Venezuelan Bolívar', nameKo: '베네수엘라 볼리바르', symbol: 'Bs', flag: '🇻🇪' },
  { code: 'crc', name: 'Costa Rican Colón', nameKo: '코스타리카 콜론', symbol: '₡', flag: '🇨🇷' },
  { code: 'dop', name: 'Dominican Peso', nameKo: '도미니카 페소', symbol: 'RD$', flag: '🇩🇴' },
  { code: 'gtq', name: 'Guatemalan Quetzal', nameKo: '과테말라 케찰', symbol: 'Q', flag: '🇬🇹' },
  { code: 'hnl', name: 'Honduran Lempira', nameKo: '온두라스 렘피라', symbol: 'L', flag: '🇭🇳' },
  { code: 'nio', name: 'Nicaraguan Córdoba', nameKo: '니카라과 코르도바', symbol: 'C$', flag: '🇳🇮' },
  { code: 'pab', name: 'Panamanian Balboa', nameKo: '파나마 발보아', symbol: 'B/.', flag: '🇵🇦' },
  { code: 'jmd', name: 'Jamaican Dollar', nameKo: '자메이카 달러', symbol: 'J$', flag: '🇯🇲' },
  { code: 'ttd', name: 'Trinidad Dollar', nameKo: '트리니다드 달러', symbol: 'TT$', flag: '🇹🇹' },
  { code: 'htg', name: 'Haitian Gourde', nameKo: '아이티 구르드', symbol: 'G', flag: '🇭🇹' },
  { code: 'bzd', name: 'Belize Dollar', nameKo: '벨리즈 달러', symbol: 'BZ$', flag: '🇧🇿' },
  { code: 'gyd', name: 'Guyanese Dollar', nameKo: '가이아나 달러', symbol: 'GY$', flag: '🇬🇾' },
  { code: 'srd', name: 'Surinamese Dollar', nameKo: '수리남 달러', symbol: 'SR$', flag: '🇸🇷' },

  // ── Europe ──
  { code: 'eur', name: 'Euro', nameKo: '유로', symbol: '€', flag: '🇪🇺' },
  { code: 'gbp', name: 'British Pound', nameKo: '영국 파운드', symbol: '£', flag: '🇬🇧' },
  { code: 'chf', name: 'Swiss Franc', nameKo: '스위스 프랑', symbol: 'CHF', flag: '🇨🇭' },
  { code: 'sek', name: 'Swedish Krona', nameKo: '스웨덴 크로나', symbol: 'kr', flag: '🇸🇪' },
  { code: 'nok', name: 'Norwegian Krone', nameKo: '노르웨이 크로네', symbol: 'kr', flag: '🇳🇴' },
  { code: 'dkk', name: 'Danish Krone', nameKo: '덴마크 크로네', symbol: 'kr', flag: '🇩🇰' },
  { code: 'pln', name: 'Polish Zloty', nameKo: '폴란드 즐로티', symbol: 'zł', flag: '🇵🇱' },
  { code: 'czk', name: 'Czech Koruna', nameKo: '체코 코루나', symbol: 'Kč', flag: '🇨🇿' },
  { code: 'huf', name: 'Hungarian Forint', nameKo: '헝가리 포린트', symbol: 'Ft', flag: '🇭🇺' },
  { code: 'ron', name: 'Romanian Leu', nameKo: '루마니아 레우', symbol: 'lei', flag: '🇷🇴' },
  { code: 'bgn', name: 'Bulgarian Lev', nameKo: '불가리아 레프', symbol: 'лв', flag: '🇧🇬' },
  { code: 'isk', name: 'Icelandic Krona', nameKo: '아이슬란드 크로나', symbol: 'kr', flag: '🇮🇸' },
  { code: 'rsd', name: 'Serbian Dinar', nameKo: '세르비아 디나르', symbol: 'din', flag: '🇷🇸' },
  { code: 'all', name: 'Albanian Lek', nameKo: '알바니아 레크', symbol: 'L', flag: '🇦🇱' },
  { code: 'mkd', name: 'Macedonian Denar', nameKo: '마케도니아 디나르', symbol: 'ден', flag: '🇲🇰' },
  { code: 'bam', name: 'Bosnian Mark', nameKo: '보스니아 마르크', symbol: 'KM', flag: '🇧🇦' },
  { code: 'mdl', name: 'Moldovan Leu', nameKo: '몰도바 레우', symbol: 'L', flag: '🇲🇩' },
  { code: 'uah', name: 'Ukrainian Hryvnia', nameKo: '우크라이나 흐리브냐', symbol: '₴', flag: '🇺🇦' },
  { code: 'byn', name: 'Belarusian Ruble', nameKo: '벨라루스 루블', symbol: 'Br', flag: '🇧🇾' },
  { code: 'gel', name: 'Georgian Lari', nameKo: '조지아 라리', symbol: '₾', flag: '🇬🇪' },
  { code: 'rub', name: 'Russian Ruble', nameKo: '러시아 루블', symbol: '₽', flag: '🇷🇺' },
  { code: 'try', name: 'Turkish Lira', nameKo: '터키 리라', symbol: '₺', flag: '🇹🇷' },

  // ── Asia-Pacific ──
  { code: 'krw', name: 'South Korean Won', nameKo: '대한민국 원', symbol: '₩', flag: '🇰🇷' },
  { code: 'jpy', name: 'Japanese Yen', nameKo: '일본 엔', symbol: '¥', flag: '🇯🇵' },
  { code: 'cny', name: 'Chinese Yuan', nameKo: '중국 위안', symbol: '¥', flag: '🇨🇳' },
  { code: 'hkd', name: 'Hong Kong Dollar', nameKo: '홍콩 달러', symbol: 'HK$', flag: '🇭🇰' },
  { code: 'twd', name: 'Taiwan Dollar', nameKo: '대만 달러', symbol: 'NT$', flag: '🇹🇼' },
  { code: 'sgd', name: 'Singapore Dollar', nameKo: '싱가포르 달러', symbol: 'S$', flag: '🇸🇬' },
  { code: 'myr', name: 'Malaysian Ringgit', nameKo: '말레이시아 링깃', symbol: 'RM', flag: '🇲🇾' },
  { code: 'thb', name: 'Thai Baht', nameKo: '태국 바트', symbol: '฿', flag: '🇹🇭' },
  { code: 'idr', name: 'Indonesian Rupiah', nameKo: '인도네시아 루피아', symbol: 'Rp', flag: '🇮🇩' },
  { code: 'php', name: 'Philippine Peso', nameKo: '필리핀 페소', symbol: '₱', flag: '🇵🇭' },
  { code: 'vnd', name: 'Vietnamese Dong', nameKo: '베트남 동', symbol: '₫', flag: '🇻🇳' },
  { code: 'inr', name: 'Indian Rupee', nameKo: '인도 루피', symbol: '₹', flag: '🇮🇳' },
  { code: 'pkr', name: 'Pakistani Rupee', nameKo: '파키스탄 루피', symbol: 'Rs', flag: '🇵🇰' },
  { code: 'bdt', name: 'Bangladeshi Taka', nameKo: '방글라데시 타카', symbol: '৳', flag: '🇧🇩' },
  { code: 'lkr', name: 'Sri Lankan Rupee', nameKo: '스리랑카 루피', symbol: 'Rs', flag: '🇱🇰' },
  { code: 'npr', name: 'Nepalese Rupee', nameKo: '네팔 루피', symbol: 'Rs', flag: '🇳🇵' },
  { code: 'mmk', name: 'Myanmar Kyat', nameKo: '미얀마 짯', symbol: 'K', flag: '🇲🇲' },
  { code: 'khr', name: 'Cambodian Riel', nameKo: '캄보디아 리엘', symbol: '៛', flag: '🇰🇭' },
  { code: 'lak', name: 'Laotian Kip', nameKo: '라오스 킵', symbol: '₭', flag: '🇱🇦' },
  { code: 'mnt', name: 'Mongolian Tugrik', nameKo: '몽골 투그리크', symbol: '₮', flag: '🇲🇳' },
  { code: 'kzt', name: 'Kazakh Tenge', nameKo: '카자흐스탄 텡게', symbol: '₸', flag: '🇰🇿' },
  { code: 'uzs', name: 'Uzbek Som', nameKo: '우즈베키스탄 솜', symbol: 'soʻm', flag: '🇺🇿' },
  { code: 'kgs', name: 'Kyrgyz Som', nameKo: '키르기스스탄 솜', symbol: 'сом', flag: '🇰🇬' },
  { code: 'tjs', name: 'Tajik Somoni', nameKo: '타지키스탄 소모니', symbol: 'SM', flag: '🇹🇯' },
  { code: 'tmt', name: 'Turkmen Manat', nameKo: '투르크메니스탄 마나트', symbol: 'T', flag: '🇹🇲' },
  { code: 'azn', name: 'Azerbaijani Manat', nameKo: '아제르바이잔 마나트', symbol: '₼', flag: '🇦🇿' },
  { code: 'amd', name: 'Armenian Dram', nameKo: '아르메니아 드람', symbol: '֏', flag: '🇦🇲' },
  { code: 'bnd', name: 'Brunei Dollar', nameKo: '브루나이 달러', symbol: 'B$', flag: '🇧🇳' },
  { code: 'mvr', name: 'Maldivian Rufiyaa', nameKo: '몰디브 루피야', symbol: 'Rf', flag: '🇲🇻' },
  { code: 'afn', name: 'Afghan Afghani', nameKo: '아프가니스탄 아프가니', symbol: '؋', flag: '🇦🇫' },
  { code: 'btn', name: 'Bhutanese Ngultrum', nameKo: '부탄 눌트럼', symbol: 'Nu', flag: '🇧🇹' },
  { code: 'aud', name: 'Australian Dollar', nameKo: '호주 달러', symbol: 'A$', flag: '🇦🇺' },
  { code: 'nzd', name: 'New Zealand Dollar', nameKo: '뉴질랜드 달러', symbol: 'NZ$', flag: '🇳🇿' },
  { code: 'fjd', name: 'Fijian Dollar', nameKo: '피지 달러', symbol: 'FJ$', flag: '🇫🇯' },
  { code: 'pgk', name: 'Papua New Guinean Kina', nameKo: '파푸아뉴기니 키나', symbol: 'K', flag: '🇵🇬' },
  { code: 'xpf', name: 'CFP Franc', nameKo: 'CFP 프랑', symbol: '₣', flag: '🇵🇫' },
  { code: 'wst', name: 'Samoan Tala', nameKo: '사모아 탈라', symbol: 'WS$', flag: '🇼🇸' },
  { code: 'top', name: 'Tongan Paʻanga', nameKo: '통가 파앙가', symbol: 'T$', flag: '🇹🇴' },
  { code: 'vuv', name: 'Vanuatu Vatu', nameKo: '바누아투 바투', symbol: 'VT', flag: '🇻🇺' },
  { code: 'sbd', name: 'Solomon Islands Dollar', nameKo: '솔로몬제도 달러', symbol: 'SI$', flag: '🇸🇧' },

  // ── Middle East ──
  { code: 'aed', name: 'UAE Dirham', nameKo: 'UAE 디르함', symbol: 'د.إ', flag: '🇦🇪' },
  { code: 'sar', name: 'Saudi Riyal', nameKo: '사우디 리얄', symbol: '﷼', flag: '🇸🇦' },
  { code: 'ils', name: 'Israeli Shekel', nameKo: '이스라엘 셰켈', symbol: '₪', flag: '🇮🇱' },
  { code: 'jod', name: 'Jordanian Dinar', nameKo: '요르단 디나르', symbol: 'JD', flag: '🇯🇴' },
  { code: 'kwd', name: 'Kuwaiti Dinar', nameKo: '쿠웨이트 디나르', symbol: 'KD', flag: '🇰🇼' },
  { code: 'bhd', name: 'Bahraini Dinar', nameKo: '바레인 디나르', symbol: 'BD', flag: '🇧🇭' },
  { code: 'omr', name: 'Omani Rial', nameKo: '오만 리알', symbol: 'OMR', flag: '🇴🇲' },
  { code: 'qar', name: 'Qatari Riyal', nameKo: '카타르 리얄', symbol: 'QR', flag: '🇶🇦' },
  { code: 'iqd', name: 'Iraqi Dinar', nameKo: '이라크 디나르', symbol: 'ع.د', flag: '🇮🇶' },
  { code: 'irr', name: 'Iranian Rial', nameKo: '이란 리알', symbol: '﷼', flag: '🇮🇷' },
  { code: 'lbp', name: 'Lebanese Pound', nameKo: '레바논 파운드', symbol: '£', flag: '🇱🇧' },
  { code: 'egp', name: 'Egyptian Pound', nameKo: '이집트 파운드', symbol: '£', flag: '🇪🇬' },
  { code: 'yer', name: 'Yemeni Rial', nameKo: '예멘 리알', symbol: '﷼', flag: '🇾🇪' },
  { code: 'syp', name: 'Syrian Pound', nameKo: '시리아 파운드', symbol: '£', flag: '🇸🇾' },

  // ── Africa ──
  { code: 'zar', name: 'South African Rand', nameKo: '남아공 랜드', symbol: 'R', flag: '🇿🇦' },
  { code: 'ngn', name: 'Nigerian Naira', nameKo: '나이지리아 나이라', symbol: '₦', flag: '🇳🇬' },
  { code: 'kes', name: 'Kenyan Shilling', nameKo: '케냐 실링', symbol: 'KSh', flag: '🇰🇪' },
  { code: 'ghs', name: 'Ghanaian Cedi', nameKo: '가나 세디', symbol: '₵', flag: '🇬🇭' },
  { code: 'mad', name: 'Moroccan Dirham', nameKo: '모로코 디르함', symbol: 'MAD', flag: '🇲🇦' },
  { code: 'tzs', name: 'Tanzanian Shilling', nameKo: '탄자니아 실링', symbol: 'TSh', flag: '🇹🇿' },
  { code: 'etb', name: 'Ethiopian Birr', nameKo: '에티오피아 비르', symbol: 'Br', flag: '🇪🇹' },
  { code: 'ugx', name: 'Ugandan Shilling', nameKo: '우간다 실링', symbol: 'USh', flag: '🇺🇬' },
  { code: 'dzd', name: 'Algerian Dinar', nameKo: '알제리 디나르', symbol: 'DA', flag: '🇩🇿' },
  { code: 'tnd', name: 'Tunisian Dinar', nameKo: '튀니지 디나르', symbol: 'DT', flag: '🇹🇳' },
  { code: 'lyd', name: 'Libyan Dinar', nameKo: '리비아 디나르', symbol: 'LD', flag: '🇱🇾' },
  { code: 'xof', name: 'West African CFA Franc', nameKo: '서아프리카 CFA 프랑', symbol: 'CFA', flag: '🇸🇳' },
  { code: 'xaf', name: 'Central African CFA Franc', nameKo: '중앙아프리카 CFA 프랑', symbol: 'FCFA', flag: '🇨🇲' },
  { code: 'zmw', name: 'Zambian Kwacha', nameKo: '잠비아 콰차', symbol: 'ZK', flag: '🇿🇲' },
  { code: 'mzn', name: 'Mozambican Metical', nameKo: '모잠비크 메티칼', symbol: 'MT', flag: '🇲🇿' },
  { code: 'aoa', name: 'Angolan Kwanza', nameKo: '앙골라 콴자', symbol: 'Kz', flag: '🇦🇴' },
  { code: 'rwf', name: 'Rwandan Franc', nameKo: '르완다 프랑', symbol: 'RF', flag: '🇷🇼' },
  { code: 'bwp', name: 'Botswana Pula', nameKo: '보츠와나 풀라', symbol: 'P', flag: '🇧🇼' },
  { code: 'mur', name: 'Mauritian Rupee', nameKo: '모리셔스 루피', symbol: 'Rs', flag: '🇲🇺' },
  { code: 'nad', name: 'Namibian Dollar', nameKo: '나미비아 달러', symbol: 'N$', flag: '🇳🇦' },
  { code: 'sdg', name: 'Sudanese Pound', nameKo: '수단 파운드', symbol: 'SDG', flag: '🇸🇩' },
  { code: 'mga', name: 'Malagasy Ariary', nameKo: '마다가스카르 아리아리', symbol: 'Ar', flag: '🇲🇬' },
  { code: 'scr', name: 'Seychellois Rupee', nameKo: '세이셸 루피', symbol: 'Rs', flag: '🇸🇨' },
  { code: 'cve', name: 'Cape Verdean Escudo', nameKo: '카보베르데 에스쿠도', symbol: '$', flag: '🇨🇻' },
  { code: 'gmd', name: 'Gambian Dalasi', nameKo: '감비아 달라시', symbol: 'D', flag: '🇬🇲' },
  { code: 'mwk', name: 'Malawian Kwacha', nameKo: '말라위 콰차', symbol: 'MK', flag: '🇲🇼' },
  { code: 'cdf', name: 'Congolese Franc', nameKo: '콩고 프랑', symbol: 'FC', flag: '🇨🇩' },
  { code: 'gnf', name: 'Guinean Franc', nameKo: '기니 프랑', symbol: 'FG', flag: '🇬🇳' },
  { code: 'sos', name: 'Somali Shilling', nameKo: '소말리아 실링', symbol: 'Sh', flag: '🇸🇴' },
  { code: 'ern', name: 'Eritrean Nakfa', nameKo: '에리트레아 나크파', symbol: 'Nfk', flag: '🇪🇷' },
  { code: 'sll', name: 'Sierra Leonean Leone', nameKo: '시에라리온 리온', symbol: 'Le', flag: '🇸🇱' },
  { code: 'mru', name: 'Mauritanian Ouguiya', nameKo: '모리타니 우기야', symbol: 'UM', flag: '🇲🇷' },
  { code: 'lrd', name: 'Liberian Dollar', nameKo: '라이베리아 달러', symbol: 'L$', flag: '🇱🇷' },
  { code: 'szl', name: 'Eswatini Lilangeni', nameKo: '에스와티니 릴랑게니', symbol: 'E', flag: '🇸🇿' },
  { code: 'lsl', name: 'Lesotho Loti', nameKo: '레소토 로티', symbol: 'M', flag: '🇱🇸' },
  { code: 'bif', name: 'Burundian Franc', nameKo: '부룬디 프랑', symbol: 'FBu', flag: '🇧🇮' },
  { code: 'djf', name: 'Djiboutian Franc', nameKo: '지부티 프랑', symbol: 'Fdj', flag: '🇩🇯' },
  { code: 'kmf', name: 'Comorian Franc', nameKo: '코모로 프랑', symbol: 'CF', flag: '🇰🇲' },
  { code: 'ssp', name: 'South Sudanese Pound', nameKo: '남수단 파운드', symbol: '£', flag: '🇸🇸' },
  { code: 'stn', name: 'São Tomé Dobra', nameKo: '상투메 도브라', symbol: 'Db', flag: '🇸🇹' },
];

/** 코드로 통화 찾기. 법정화폐 → 암호화폐 순서 조회. */
export function getCurrency(code: string): Currency | undefined {
  const lc = code.toLowerCase();
  return CURRENCIES.find(c => c.code === lc) ?? CRYPTO_CURRENCIES.find(c => c.code === lc);
}

/** 전체 통화 코드 목록. */
export const CURRENCY_CODES = CURRENCIES.map(c => c.code);
